#making cripsy forms fail loudl
CRISPY_FAIL_SILENTLY = True

SESSION_COOKIE_DAYS = 90
SESSION_COOKIE_AGE = 60 * 60 * 24 * SESSION_COOKIE_DAYS

PROD_TEMPLATE_CONTEXT_PROCESSORS = (
    )

PROD_MIDDLEWARE_CLASSES = ()

PROD_INSTALLED_APPS = (
    ) 