from django.db.models import signals
from tags.models import Tag


def create_tags(app, created_models, **kwargs):
        Tag.objects.get_or_create(name="Architecture")
        Tag.objects.get_or_create(name="Art")
        Tag.objects.get_or_create(name="Books")
        Tag.objects.get_or_create(name="Cars & Motorcycles")
        Tag.objects.get_or_create(name="DIY & Crafts")
        Tag.objects.get_or_create(name="Design")
        Tag.objects.get_or_create(name="Drink")
        Tag.objects.get_or_create(name="Education")
        Tag.objects.get_or_create(name="Fashion")
        Tag.objects.get_or_create(name="Film, Music")
        Tag.objects.get_or_create(name="Food")
        Tag.objects.get_or_create(name="Games")
        Tag.objects.get_or_create(name="Gardening")
        Tag.objects.get_or_create(name="Geeg")
        Tag.objects.get_or_create(name="Hair & beauty")
        Tag.objects.get_or_create(name="Health & fitness")
        Tag.objects.get_or_create(name="History")
        Tag.objects.get_or_create(name="Holidays & Events")
        Tag.objects.get_or_create(name="Home Decor")
        Tag.objects.get_or_create(name="Humor")
        Tag.objects.get_or_create(name="Illustrations")
        Tag.objects.get_or_create(name="Kids")
        Tag.objects.get_or_create(name="Men")
        Tag.objects.get_or_create(name="Outdoors")
        Tag.objects.get_or_create(name="Photography")
        Tag.objects.get_or_create(name="Products")
        Tag.objects.get_or_create(name="Quotes")
        Tag.objects.get_or_create(name="Science a Nature")
        Tag.objects.get_or_create(name="Sports")
        Tag.objects.get_or_create(name="Technology")
        Tag.objects.get_or_create(name="Travel")
        Tag.objects.get_or_create(name="Weddings")
        Tag.objects.get_or_create(name="Women")
        Tag.objects.get_or_create(name="Videos")

signals.post_syncdb.connect(create_tags, dispatch_uid=Tag)
